# Generated by Django 6.0 on 2025-12-16 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=100)),
                ('probabilita_priori', models.FloatField()),
            ],
            options={
                'verbose_name': 'Evento per oracolo',
                'verbose_name_plural': 'Eventi per oracolo',
            },
        ),
        migrations.CreateModel(
            name='TentativiDiLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_failed_attempts', models.IntegerField(default=0)),
                ('otp_is_blocked', models.BooleanField(default=False)),
                ('otp_blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentativo di Login',
                'verbose_name_plural': 'Tentativi di Login',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProva', models.CharField(max_length=100)),
                ('prob1', models.BooleanField(default=False)),
                ('prob2', models.BooleanField(default=False)),
                ('prob3', models.BooleanField(default=False)),
                ('probabilita_condizionata', models.FloatField()),
                ('idEvento1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento1', to='Ledger_Logistic.evento')),
                ('idEvento2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento2', to='Ledger_Logistic.evento')),
                ('idEvento3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento3', to='Ledger_Logistic.evento')),
            ],
            options={
                'verbose_name': 'Prova per oracolo',
                'verbose_name_plural': 'Prove per oracolo',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Cognome')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data registrazione')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='CodiceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=6)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('scade_il', models.DateTimeField()),
                ('usato', models.BooleanField(default=False)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codici_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codice OTP',
                'verbose_name_plural': 'Codici OTP',
                'ordering': ['-creato_il'],
            },
        ),
    ]
