# Generated by Django 6.0 on 2026-01-16 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Visualizzatore File',
                'verbose_name_plural': 'Visualizzatore File',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=100)),
                ('probabilita_priori', models.FloatField()),
            ],
            options={
                'verbose_name': 'Evento per oracolo',
                'verbose_name_plural': 'Eventi per oracolo',
            },
        ),
        migrations.CreateModel(
            name='MessaggioContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome e Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('servizio', models.CharField(blank=True, max_length=50, verbose_name='Servizio di interesse')),
                ('messaggio', models.TextField(verbose_name='Messaggio')),
                ('data_invio', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
                ('letto', models.BooleanField(default=False, verbose_name='Letto')),
            ],
            options={
                'verbose_name': 'Messaggio di Contatto',
                'verbose_name_plural': 'Messaggi di Contatto',
                'ordering': ['-data_invio'],
            },
        ),
        migrations.CreateModel(
            name='Spedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_tracciamento', models.CharField(max_length=20, unique=True, verbose_name='Codice Tracciamento')),
                ('indirizzo_consegna', models.TextField(verbose_name='Indirizzo di Consegna')),
                ('citta', models.CharField(max_length=100, verbose_name='Città')),
                ('cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('provincia', models.CharField(max_length=2, verbose_name='Provincia')),
                ('grandezza', models.CharField(choices=[('piccolo', 'Piccolo'), ('medio', 'Medio'), ('grande', 'Grande')], default='medio', max_length=10, verbose_name='Grandezza Pacco')),
                ('descrizione', models.TextField(verbose_name='Descrizione Ordine')),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_elaborazione', 'In Elaborazione'), ('in_transito', 'In Transito'), ('in_consegna', 'In Consegna'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20, verbose_name='Stato')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('carta', 'Carta di credito'), ('cash', 'Pagamento alla consegna')], max_length=10)),
                ('traffico', models.BooleanField(blank=True, default=None, null=True, verbose_name='Presenza Traffico')),
                ('veicolo_disponibile', models.BooleanField(blank=True, default=None, null=True, verbose_name='Veicolo Disponibile')),
                ('meteo_sfavorevole', models.BooleanField(blank=True, default=None, null=True, verbose_name='Meteo Sfavorevole')),
                ('conferma_del_gestore_di_pagamento', models.BooleanField(blank=True, default=None, null=True, verbose_name='conferma del gestore di pagamento')),
                ('fattura_emessa', models.BooleanField(blank=True, default=None, null=True, verbose_name='Fattura Emessa')),
                ('gps', models.BooleanField(blank=True, default=None, null=True, verbose_name='GPS')),
                ('conferma_cliente', models.BooleanField(blank=True, default=None, null=True, verbose_name='Conferma del Cliente')),
                ('disponibilita_corriere', models.BooleanField(default=False, verbose_name='Disponibilità del Corriere')),
            ],
            options={
                'verbose_name': 'Spedizione',
                'verbose_name_plural': 'Spedizioni',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='TentativiDiLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_failed_attempts', models.IntegerField(default=0)),
                ('otp_is_blocked', models.BooleanField(default=False)),
                ('otp_blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentativo di Login',
                'verbose_name_plural': 'Tentativi di Login',
            },
        ),
        migrations.CreateModel(
            name='TentativiRecuperoPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_failed_attempts', models.IntegerField(default=0)),
                ('otp_is_blocked', models.BooleanField(default=False)),
                ('otp_blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentativo di Recupero Password',
                'verbose_name_plural': 'Tentativi di Recupero Password',
            },
        ),
        migrations.CreateModel(
            name='Probabilita_condizionate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProva', models.CharField(max_length=100)),
                ('evento1', models.BooleanField(blank=True, default=False, null=True)),
                ('evento2', models.BooleanField(blank=True, default=False, null=True)),
                ('evento3', models.BooleanField(blank=True, default=False, null=True)),
                ('probabilita_condizionata', models.TextField()),
                ('idEvento1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento1', to='Ledger_Logistic.evento')),
                ('idEvento2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento2', to='Ledger_Logistic.evento')),
                ('idEvento3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prove_evento3', to='Ledger_Logistic.evento')),
            ],
            options={
                'verbose_name': 'Prova per oracolo',
                'verbose_name_plural': 'Prove per oracolo',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeReclamo', models.TextField(choices=[('Spedizione non effettuata correttamente', 'Spedizione non effettuata correttamente'), ('Verifica pagamento', 'Verifica pagamento'), ('Ritardo di consegna', 'Ritardo di consegna')], verbose_name='nomeReclamo')),
                ('descrizione', models.CharField(max_length=600, verbose_name='Descrizione Reclamo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Reclamo')),
                ('risolto', models.BooleanField(default=False, verbose_name='Risolto')),
                ('esito', models.TextField(choices=[('Non verificato', 'Non verificato'), ('Accettato', 'Accettato'), ('Rifiutato', 'Rifiutato')], verbose_name='Esito')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='Ledger_Logistic.evento', verbose_name='Evento')),
                ('spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizioni', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Cognome')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('ruolo', models.CharField(default='cliente', max_length=10, verbose_name='Ruolo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data registrazione')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.AddField(
            model_name='spedizione',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizioni', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='corriere',
            field=models.ForeignKey(blank=True, limit_choices_to={'ruolo': 'corriere'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consegne', to=settings.AUTH_USER_MODEL, verbose_name='Corriere Assegnato'),
        ),
        migrations.CreateModel(
            name='CodiceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=6)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('scade_il', models.DateTimeField()),
                ('usato', models.BooleanField(default=False)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codici_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codice OTP',
                'verbose_name_plural': 'Codici OTP',
                'ordering': ['-creato_il'],
            },
        ),
    ]
