# Generated by Django 6.0 on 2025-12-16 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentatividilogin',
            name='otp_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentatividilogin',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentatividilogin',
            name='otp_is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tentatividilogin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='CodiceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=6)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('scade_il', models.DateTimeField()),
                ('usato', models.BooleanField(default=False)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codici_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codice OTP',
                'verbose_name_plural': 'Codici OTP',
                'ordering': ['-creato_il'],
            },
        ),
    ]
