# Generated by Django 6.0 on 2025-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='prob1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prova',
            name='prob2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prova',
            name='prob3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
