# Generated by Django 6.0 on 2026-01-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeReclamo', models.TextField(choices=[('Spedizione non effettuata correttamente', 'Spedizione non effettuata correttamente'), ('Verifica pagamento', 'Verifica pagamento'), ('Ritardo di consegna', 'Ritardo di consegna')], verbose_name='nomeReclamo')),
                ('descrizione', models.CharField(max_length=600, verbose_name='Descrizione Reclamo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Reclamo')),
                ('risolto', models.BooleanField(default=False, verbose_name='Risolto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='Ledger_Logistic.evento', verbose_name='Evento')),
                ('spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizioni', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
            options={
                'verbose_name': 'Spedizione',
                'verbose_name_plural': 'Spedizioni',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
