# Generated by Django 6.0 on 2025-12-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0001_initial'),
    ]

    operations = [
    ]
