# Generated by Django 6.0 on 2025-12-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0002_auto_20251215_1828'),
    ]

    operations = [
    ]
