# Generated by Django 6.0 on 2025-12-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0002_tentatividilogin_otp_blocked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=100)),
                ('probabilita_priori', models.FloatField(max_length=5)),
            ],
            options={
                'verbose_name': 'Evento_per_oracolo',
                'verbose_name_plural': 'Eventi_per_oracolo',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProva', models.CharField(max_length=100)),
                ('probabilita_condizionata', models.FloatField(max_length=5)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evento_per_oracolo', to='Ledger_Logistic.evento')),
            ],
            options={
                'verbose_name': 'Prova_per_oracolo',
                'verbose_name_plural': 'Prove_per_oracolo',
            },
        ),
    ]
