# Generated by Django 6.0 on 2025-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0004_tentativirecuperopassword_otp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessaggioContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome e Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('servizio', models.CharField(blank=True, max_length=50, verbose_name='Servizio di interesse')),
                ('messaggio', models.TextField(verbose_name='Messaggio')),
                ('data_invio', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
                ('letto', models.BooleanField(default=False, verbose_name='Letto')),
            ],
            options={
                'verbose_name': 'Messaggio di Contatto',
                'verbose_name_plural': 'Messaggi di Contatto',
                'ordering': ['-data_invio'],
            },
        ),
    ]
