# Generated by Django 6.0 on 2025-12-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0005_messaggiocontatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(default='cliente', max_length=10, verbose_name='Ruolo'),
        ),
    ]
