# Generated by Django 6.0 on 2025-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0005_messaggiocontatto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Visualizzatore File',
                'verbose_name_plural': 'Visualizzatore File',
                'managed': False,
            },
        ),
    ]
