# Generated by Django 6.0 on 2025-12-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0006_utente_ruolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_tracciamento', models.CharField(max_length=20, unique=True, verbose_name='Codice Tracciamento')),
                ('indirizzo_consegna', models.TextField(verbose_name='Indirizzo di Consegna')),
                ('citta', models.CharField(max_length=100, verbose_name='Città')),
                ('cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('provincia', models.CharField(max_length=2, verbose_name='Provincia')),
                ('grandezza', models.CharField(choices=[('piccolo', 'Piccolo'), ('medio', 'Medio'), ('grande', 'Grande')], default='medio', max_length=10, verbose_name='Grandezza Pacco')),
                ('descrizione', models.TextField(verbose_name='Descrizione Ordine')),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_elaborazione', 'In Elaborazione'), ('in_transito', 'In Transito'), ('in_consegna', 'In Consegna'), ('consegnato', 'Consegnato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20, verbose_name='Stato')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizioni', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('corriere', models.ForeignKey(blank=True, limit_choices_to={'ruolo': 'corriere'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consegne', to=settings.AUTH_USER_MODEL, verbose_name='Corriere Assegnato')),
            ],
            options={
                'verbose_name': 'Spedizione',
                'verbose_name_plural': 'Spedizioni',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
