# Generated by Django 6.0 on 2025-12-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0006_fileviewer'),
        ('Ledger_Logistic', '0007_spedizione'),
    ]

    operations = [
    ]
