# Generated by Django 6.0 on 2025-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0008_merge_0006_fileviewer_0007_spedizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='traffico',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Presenza Traffico'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='veicolo_disponibile',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Veicolo Disponibile'),
        ),
    ]
