# Generated by Django 6.0 on 2025-12-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0009_spedizione_traffico_spedizione_veicolo_disponibile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Charge ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo (€)')),
                ('valuta', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('stato', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('succeeded', 'Completata'), ('failed', 'Fallita'), ('canceled', 'Annullata'), ('refunded', 'Rimborsata')], default='pending', max_length=20, verbose_name='Stato Transazione')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('data_aggiornamento', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('data_completamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Completamento')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email Cliente')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metodo di Pagamento')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('stripe_response_data', models.JSONField(blank=True, null=True, verbose_name='Dati Risposta Stripe')),
                ('spedizione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transazione', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
            options={
                'verbose_name': 'Transazione',
                'verbose_name_plural': 'Transazioni',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
