# Generated by Django 6.0 on 2026-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0010_transazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='conferma_cliente',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Conferma del Cliente'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='disponibilita_corriere',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Disponibilità del Corriere'),
        ),
        
        migrations.AddField(
            model_name='spedizione',
            name='gps',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='GPS'),
        ),
        
        
        
    ]
