# Generated by Django 6.0 on 2026-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0011_spedizione_conferma_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spedizione',
            name='disponibilita_corriere',
            field=models.BooleanField(default=False, verbose_name='Disponibilità del Corriere'),
        ),
    ]
