# Generated by Django 6.0 on 2026-01-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0012_spedizione_conferma_del_gestore_di_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='conferma_del_gestore_di_pagamento',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='conferma del gestore di pagamento'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='fattura_emessa',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Fattura Emessa'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='meteo_sfavorevole',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Meteo Sfavorevole'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('carta', 'Carta di credito'), ('cash', 'Pagamento alla consegna')], max_length=10),
        ),
        migrations.CreateModel(
            name='Reclami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(choices=[('spedizione effettuata con successo', 'spedizione effettuata con successo'), ('pagamento ricevuto con successo', 'pagamento ricevuto con successo'), ('ritardo di consegna', 'ritardo di consegna')], verbose_name='tipo')),
                ('descrizione', models.TextField(verbose_name='Descrizione Reclamo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Reclamo')),
                ('risolto', models.BooleanField(default=False, verbose_name='Risolto')),
                ('id_spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizione', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
        ),
        migrations.DeleteModel(
            name='Transazione',
        ),
    ]
