# Generated by Django 6.0 on 2026-01-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0012_spedizione_conferma_del_gestore_di_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(choices=[('spedizione effettuata con successo', 'spedizione effettuata con successo'), ('pagamento ricevuto con successo', 'pagamento ricevuto con successo'), ('ritardo di consegna', 'ritardo di consegna')], verbose_name='tipo')),
                ('descrizione', models.TextField(verbose_name='Descrizione Reclamo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Reclamo')),
                ('risolto', models.BooleanField(default=False, verbose_name='Risolto')),
                ('id_spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizione', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
        )
    ]
