# Generated by Django 6.0 on 2026-01-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger_Logistic', '0012_spedizione_conferma_del_gestore_di_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spedizione',
            options={},
        ),
        migrations.AddField(
            model_name='spedizione',
            name='conferma_del_gestore_di_pagamento',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='conferma del gestore di pagamento'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='fattura_emessa',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Fattura Emessa'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='meteo_sfavorevole',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Meteo Sfavorevole'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('carta', 'Carta di credito'), ('cash', 'Pagamento alla consegna')], max_length=10),
        ),
        migrations.CreateModel(
            name='Reclami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeReclamo', models.TextField(choices=[('Spedizione non effettuata correttamente', 'Spedizione non effettuata correttamente'), ('Verifica pagamento', 'Verifica pagamento'), ('Ritardo di consegna', 'Ritardo di consegna')], verbose_name='nomeReclamo')),
                ('descrizione', models.TextField(verbose_name='Descrizione Reclamo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Reclamo')),
                ('risolto', models.BooleanField(default=False, verbose_name='Risolto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='Ledger_Logistic.evento', verbose_name='Evento')),
                ('spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spedizioni', to='Ledger_Logistic.spedizione', verbose_name='Spedizione')),
            ],
            options={
                'verbose_name': 'Spedizione',
                'verbose_name_plural': 'Spedizioni',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.DeleteModel(
            name='Transazione',
        ),
    ]
